#!/usr/bin/env bash
# 0-change_your_home_IP
# This script modifies /etc/hosts to change localhost and facebook.com IP addresses
sudo cp /etc/hosts /etc/hosts.old

echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8   facebook.com" >> /etc/hosts
